pipeline {

    agent any

    tools {
        maven 'M3'
        jdk 'JDK8'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
                stash 'src'
            }
        }

        stage('Run tests') {
            steps {
                parallel branch1: {
                    node('master') {
                        unstash 'src'
                        sh 'mvn --batch-mode -V -U -e clean verify -Dsurefire.useFile=false -Dcucumber.options=\"--plugin json:target/cucumber-branch1.json \"'
                        cucumber fileIncludePattern: '**/cucumber-*.json', parallelTesting: true
                    }
                }, branch2: {
                    node('master') {
                        unstash 'src'
                        sh 'mvn --batch-mode -V -U -e clean verify -Dsurefire.useFile=false -Dcucumber.options=\"--plugin json:target/cucumber-branch2.json\"'
                        cucumber fileIncludePattern: '**/cucumber-*.json', parallelTesting: true
                    }
                }, branch3: {
                    node('master') {
                        unstash 'src'
                        sh 'mvn --batch-mode -V -U -e clean verify -Dsurefire.useFile=false -Dcucumber.options=\"--plugin json:target/cucumber-branch3.json\"'
                        cucumber fileIncludePattern: '**/cucumber-*.json', parallelTesting: true
                    }
                }
            }
        }
    }

}
